name: Build Firmware

on:
#  push:
#    branches:
#      - "*"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    strategy:
      fail-fast: false
      matrix:
        target: [K2P]
        toolchain: [mipsel-linux-musl]
    steps:
      - uses: actions/checkout@main
      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ccache-${{ matrix.toolchain }}

      - uses: actions/setup-go@main
        with:
          go-version: '1.24.x'
          check-latest: true
          cache: false

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bison flex gperf help2man libtool-bin texinfo python3-docutils \
            autopoint gettext ccache autoconf automake liblzma-dev libltdl-dev
          echo "BUILD_DATE=$(TZ='Asia/Shanghai' date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build firmware
        run: |
          make "${{ matrix.target }}" TOOLCHAIN="${{ matrix.toolchain }}"

      - name: Show build ccache info
        run: |
          uname -a
          gcc --version
          echo "ccache stats:"
          ccache -s || true
          echo "Target: ${{ matrix.target }}"
          echo "Toolchain: ${{ matrix.toolchain }}"

      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}-${{ matrix.toolchain }}-${{ env.BUILD_DATE }}
          path: trunk/images/*.trx

      - uses: ncipollo/release-action@main
        with:
          commit: main
          tag: ${{ env.BUILD_DATE }}
          artifacts: trunk/images/*.trx
          allowUpdates: true
          omitBodyDuringUpdate: true

      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
